#ifndef MINIMALISTIC_PARSER_GENERATOR_AMBIGUOUSRULENODE_H
#define MINIMALISTIC_PARSER_GENERATOR_AMBIGUOUSRULENODE_H


#include "ASTNode.h"

class AmbiguousRuleNode : public ASTNode {
public:

};


#endif //MINIMALISTIC_PARSER_GENERATOR_AMBIGUOUSRULENODE_H
